### ISSUE TITLE
Is Munee still maintained?

### ISSUE THREAD

**Issue by webbird** [meenie/munee#57]
The latest release is more than 2 years old, so ist this still maintained?

**Comment by meenie** [comment]
Hi @webbird.  It's in a bit of a dormant stage.  In my last company it was used a lot, but since I changed jobs and moved to more of a Front-End Engineering role, I haven't had much need for it.  I've found that using tools like Grunt or Gulp are far superior than Munee.

Is there any specific that you need working and/or fixed?

**Comment by xbitstream** [comment]
It would be cool to have include rules like:
/**
 * = import xx.scss
*/
or

// = import yyy.js

etc in header comments in files (css, js).

**Comment by webbird** [comment]
Thanks for the statement.

I am on research for a solution to include in our CMS and Munee seems quite promising, but there's alot that happened in 2 years. (New PHP versions etc.)

I also checked out http://code.google.com/p/minify/, but it's not what we need.

**Comment by meenie** [comment]
@xbitstream I agree that it would be cool to do such things, but I think it's out of the realm of Munee.  I don't actually parse the contents of files and add functionality to them.

@webbird: Have you tried using Munee? If you run into any issues, I can try and help out. But for right now, it should work perfectly fine.

**Comment by webbird** [comment]
I'll take this as "yes, it is still maintained". ;) I will give it a try. Thank you.
